// Generated by CoffeeScript 1.6.2
(function() {
  var ShopAPI, ShopAndSiteAPI, SiteAPI;

  ShopAPI = require("./shop_api").ShopAPI;

  SiteAPI = require("./site_api").SiteAPI;

  ShopAndSiteAPI = require("./shop_and_site_api").ShopAndSiteAPI;

  module.exports.ShopAPI = ShopAPI;

  module.exports.SiteAPI = SiteAPI;

  module.exports.ShopAndSiteAPI = ShopAndSiteAPI;

}).call(this);
