// Generated by CoffeeScript 1.6.2
(function() {
  module.exports.extend = function(destination, source) {
    Object.extend = function(destination, source) {
      var property;

      for (property in source) {
        if (source.hasOwnProperty(property)) {
          destination[property] = source[property];
        }
      }
      return destination;
    };
    return Object.extend(destination, source);
  };

}).call(this);
